version: '3.8'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbdevuser
      - POSTGRES_PASSWORD=dbdevpass
      - POSTGRES_DB=devdb

  frontend:
    build: ./frontend
#    command: sh -c "npm i && npx tsc && npm run dev"
    command: sh -c "npm i && npx tsc && npm run dev -- --host"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data: